### PR TITLE
Upkeep

### LINKED ISSUE #211: alphavantager, riingo, Quandl Imports --> Suggests?
These packages are all basically API interfaces and thus represent potential security issues (we require security review to import them).

Because they are not really dependencies of the package*, maybe they are better off being Suggested dependencies instead?

*I removed `alphavantager` and `riingo` from `DESCRIPTION` and all tests/examples run fine. `Quandl` has some `@importFrom` in the `NAMESPACE`, but the surface of Quandl is not substantial -- AFAICT it's two internal functions in R/tq_get.R and two more in R/api-quandl.R, which could easily be converted to a Suggested dependency with namespace qualification:

https://github.com/business-science/tidyquant/blob/af56739d85e648b5c265859b01f85a683e474de0/R/tq_get.R#L561

https://github.com/business-science/tidyquant/blob/af56739d85e648b5c265859b01f85a683e474de0/R/tq_get.R#L624

https://github.com/business-science/tidyquant/blob/af56739d85e648b5c265859b01f85a683e474de0/R/api-quandl.R#L24

https://github.com/business-science/tidyquant/blob/af56739d85e648b5c265859b01f85a683e474de0/R/api-quandl.R#L57

### LINKED ISSUE #233: FB stock symbol retired, need to use META as stock symbol in all documentation
'FB' is no longer a working stock symbol.  All the examples in the docs and vignettes need to be updated to change
to 'META' as the new name for facebook.

### PR DESCRIPTION
**Pull request by olivroy**
Adds the linewidth aes to keep up with ggplot2 3.4.0 closes #232
Remove tidyverse, tidyselect dependencies
Fix tests (the S&P 600 link didn't work at first
Remove outdated `docs/` directory. (no longer needed since pkgdown is deployed with gh pages)
Move API dependencies to Suggests Close #211 
Fix the package alias issue
Remove `library()` calls to avoid namespace problems.
Change FB -> META in FANG + in all docs. close #233
Regenerate FANG by saving it as csv. then data-raw with mutate(FB =FANG)
Update pkgdown config + rename logo file to logo so that pkgdown recognizes it properly.
Since tidyverse 2.0 is now exporting lubridate. You may consider moving lubridate from depends to imports and not load it with tidyquant.

Cheers

This silences CRAN warnings + notes. R CMD CHECK passes on windows.

### CODE REVIEW

**Comment by mdancho84** [comment]
Thanks a lot for your help!! 

I'm running some checks now. 

If I don't get back to this immediately ping me. I'm working on a pytimetk which is taking my focus. So if I don't respond ping me.

**Comment by olivroy** [comment]
Sure, on my side, I will document Quandl params (without inheritparams, to make sure the docs are self-contained.

**Comment by olivroy** [comment]
I don't know if pinging works with edits @mdancho84 . so if you can run run gh checks again, it would be great!

**Comment by olivroy** [comment]
Many of the failures in the vignette is due to errors reading data from online. I fixed the docs issue + the vignette name

**Comment by mdancho84** [comment]
I just ran again.

**Comment by olivroy** [comment]
It seems that there are no CI failures now.

**Comment by mdancho84** [comment]
Nice work. I'm wondering though about the FB -> META change. Just because there is probably code out there that uses FANG and filters on FB. If I get a bunch of people complaining then I may have to revert back. And we can make an new dataset MANG.

**Comment by olivroy** [comment]
But I think this could be a "correct" breaking change, since it makes the examples using FANG now more consistent with `tq_get()`
Probably better to have the next release as 1.1.0 or 2.0.

What do you think about not loading lubridate with tidyquant? (I could open a follow-up PR)

Also, if you could provide guidance for #235, I think it would be very great. These warnings are a bit annoying. :) I may look into it too if you don't have time.

**Comment by mdancho84** [comment]
True. Let's see what happens. Could make a legacy FANG. And a NEW FANG. AKA MANG. Or something that includes NVDA now since it's the new darling in tech. 

P.S. Let me know if you want to help out with any of the other issues. Or if you want to do some software dev on other R projects and Python projects.

**Comment by olivroy** [comment]
Also, #230 can be closed.

But I was wondering if you would consider deprecating the `mutate_xy_*()` methods and like tidyverse, only support one set: NSE? I would work on that. But I think this would make the package easier to maintain and cleaner.

I also think it would be worthwhile closing old issues than can't be reproduced anymore or not valid.

> P.S. Let me know if you want to help out with any of the other issues. Or if you want to do some software dev on other R projects and Python projects.

I am interested!

**Comment by mdancho84** [comment]
I agree 100%. 

This is what I'm working on now: pytimetk: https://business-science.github.io/pytimetk/

**Pull request merged**
